services:
  playwright-tests:
    build: .
    container_name: saucedemo-tests
    env_file:
      - .env
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
      - ./allure-results:/app/allure-results
    # This allows reports generated inside the container
    # to be saved to your local machine.
